'use client';

import { useState, useEffect, useCallback } from 'react';
import type { PreservingMethod, HarvestEntry, RecipeOutput } from '@/lib/preserving-data';
import type { DiversionPlan } from '@/lib/bulk-buy-data';

// ---- Share Link (URL-based) ----

interface SharePayload {
 m: PreservingMethod;
 e: { id: string; w: number }[];
}

export function encodeShareLink(
  method: PreservingMethod,
  entries: HarvestEntry[],
  baseUrl: string
): string {
  const payload: SharePayload = {
    m: method,
    e: entries.map((entry) => ({ id: entry.produceId, w: entry.weightGrams })),
  };
  // Use a compact separator to keep the URL short
  const encoded = btoa(JSON.stringify(payload));
  const url = new URL(baseUrl);
  url.searchParams.set('r', encoded);
  return url.toString();
}

export function decodeShareLink(searchParams: string): {
 method: PreservingMethod;
  entries: HarvestEntry[];
} | null {
  try {
    const params = new URLSearchParams(searchParams);
    const raw = params.get('r');
    if (!raw) return null;
    const payload: SharePayload = JSON.parse(atob(raw));
    if (!payload.m || !Array.isArray(payload.e) || payload.e.length === 0) return null;
    // Validate method
    if (!['quick-pickle', 'ferment', 'water-bath'].includes(payload.m)) return null;
    return {
      method: payload.m,
      entries: payload.e.map((item) => ({
        produceId: item.id,
        weightGrams: Math.max(10, Math.min(2000, item.w || 150)),
      })),
    };
  } catch {
    return null;
  }
}

// ---- Types ----

export interface SavedRecipe {
  id: string;
  savedAt: string; // ISO date
  name: string; // user-friendly title
  method: PreservingMethod;
  harvestEntries: HarvestEntry[];
  recipe: RecipeOutput;
}

const STORAGE_KEY = 'balcony-to-pantry-saved-recipes';

// ---- Helpers ----

function generateId(): string {
  return Date.now().toString(36) + Math.random().toString(36).slice(2, 8);
}

function loadFromStorage(): SavedRecipe[] {
  if (typeof window === 'undefined') return [];
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    if (!Array.isArray(parsed)) return [];
    return parsed;
  } catch {
    return [];
  }
}

function saveToStorage(recipes: SavedRecipe[]) {
  if (typeof window === 'undefined') return;
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(recipes));
  } catch {
    // localStorage full or unavailable — silently fail
  }
}

// ---- Text File Export ----

export function recipeToText(recipe: RecipeOutput): string {
  const divider = '─'.repeat(44);
  const lines: string[] = [];

  lines.push(divider);
  lines.push(`  ${recipe.title}`);
  lines.push(divider);
  lines.push('');
  lines.push(`  Jar Size:    ${recipe.jarSize === 'half-pint' ? 'Half-Pint' : 'Pint'} (${recipe.jarSizeMl} ml)`);
  lines.push(`  Servings:    ${recipe.servings}`);
  lines.push(`  Method:      ${recipe.method === 'quick-pickle' ? 'Quick Pickle' : recipe.method === 'ferment' ? 'Lacto-Ferment' : 'Water-Bath Can'}`);
  lines.push('');
  lines.push('  INGREDIENTS');
  lines.push('  ' + '─'.repeat(40));
  for (const ing of recipe.ingredients) {
    const note = ing.note ? `  (${ing.note})` : '';
    lines.push(`  ${ing.amount.padEnd(10)} ${ing.name}${note}`);
  }
  lines.push('');
  lines.push('  EQUIPMENT');
  lines.push('  ' + '─'.repeat(40));
  for (const eq of recipe.equipment) {
    lines.push(`  • ${eq}`);
  }
  lines.push('');
  lines.push('  STEP-BY-STEP INSTRUCTIONS');
  lines.push('  ' + '─'.repeat(40));
  recipe.steps.forEach((step, i) => {
    lines.push('');
    lines.push(`  Step ${i + 1}:`);
    // Word-wrap the step text at ~70 chars
    const words = step.split(' ');
    let currentLine = '    ';
    for (const word of words) {
      if ((currentLine + word).length > 74) {
        lines.push(currentLine);
        currentLine = '    ' + word + ' ';
      } else {
        currentLine += word + ' ';
      }
    }
    if (currentLine.trim()) lines.push(currentLine);
  });
  lines.push('');
  lines.push('  STORAGE');
  lines.push('  ' + '─'.repeat(40));
  lines.push(`  ${recipe.storage}`);
  lines.push('');
  lines.push('  SHELF LIFE');
  lines.push('  ' + '─'.repeat(40));
  lines.push(`  ${recipe.shelfLife}`);
  lines.push('');
  lines.push('  ⚠  SAFETY NOTES');
  lines.push('  ' + '─'.repeat(40));
  lines.push(`  ${recipe.safetyNote}`);
  lines.push('');
  lines.push(divider);
  lines.push('  Generated by Balcony-to-Pantry Preserving Calculator');
  lines.push(`  Saved on ${new Date().toLocaleDateString('en-NZ', { year: 'numeric', month: 'long', day: 'numeric' })}`);
  lines.push(divider);

  return lines.join('\n');
}

export async function copyShareLink(
  method: PreservingMethod,
  entries: HarvestEntry[],
): Promise<boolean> {
  const url = encodeShareLink(method, entries, window.location.origin + window.location.pathname);
  try {
    await navigator.clipboard.writeText(url);
    return true;
  } catch {
    // Fallback: select a temporary input
    const input = document.createElement('input');
    input.value = url;
    document.body.appendChild(input);
    input.select();
    document.execCommand('copy');
    document.body.removeChild(input);
    return true;
  }
}

export function downloadRecipeText(recipe: RecipeOutput) {
  const text = recipeToText(recipe);
  const safeName = recipe.title.replace(/[^a-zA-Z0-9 ]/g, '').replace(/\s+/g, '-').toLowerCase();
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${safeName}-recipe.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ---- Diversion Plan Text Export ----

export function diversionPlanToText(
  plan: DiversionPlan,
  itemName: string,
  itemEmoji: string,
  totalLbs: number
): string {
  const divider = '─'.repeat(48);
  const lines: string[] = [];

  lines.push(divider);
  lines.push(`  ${itemEmoji} Bulk-Buy Diversion Plan: ${itemName}`);
  lines.push(divider);
  lines.push('');
  lines.push(`  Total Weight:  ${totalLbs} lbs (${plan.totalWeightGrams} g)`);
  lines.push(`  Steps:         ${plan.steps.length} processing methods`);
  lines.push('');

  plan.steps.forEach((step, i) => {
    lines.push(`  ─── Step ${i + 1}: ${step.weightLbs} lbs → ${step.method.name} ───`);
    lines.push('');
    lines.push(`  Storage:       ${step.storageLocation}`);
    lines.push(`  Space Used:    ${step.spaceUsed}`);
    lines.push(`  Processing:    ${step.processingTime}`);
    lines.push(`  Shelf Life:    ${step.shelfLife}`);
    lines.push('');
    lines.push('  Instructions:');
    // Word-wrap instructions at ~70 chars
    const words = step.instructions.split(' ');
    let currentLine = '    ';
    for (const word of words) {
      if ((currentLine + word).length > 74) {
        lines.push(currentLine);
        currentLine = '    ' + word + ' ';
      } else {
        currentLine += word + ' ';
      }
    }
    if (currentLine.trim()) lines.push(currentLine);
    lines.push('');
  });

  lines.push(divider);
  lines.push('  Generated by Balcony-to-Pantry Bulk-Buy Diversion Matrix');
  lines.push(`  ${new Date().toLocaleDateString('en-NZ', { year: 'numeric', month: 'long', day: 'numeric' })}`);
  lines.push(divider);

  return lines.join('\n');
}

export function downloadDiversionText(
  plan: DiversionPlan,
  itemName: string,
  itemEmoji: string,
  totalLbs: number
) {
  const text = diversionPlanToText(plan, itemName, itemEmoji, totalLbs);
  const safeName = itemName.replace(/[^a-zA-Z0-9 ]/g, '').replace(/\s+/g, '-').toLowerCase();
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${safeName}-${totalLbs}lbs-diversion.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ---- Hook ----

export function useRecipeStore() {
  // Lazy init reads from localStorage once on mount — no effect needed
  const [savedRecipes, setSavedRecipes] = useState<SavedRecipe[]>(() => loadFromStorage());

  // Persist to localStorage whenever savedRecipes changes
  useEffect(() => {
    saveToStorage(savedRecipes);
  }, [savedRecipes]);

  const saveRecipe = useCallback(
    (method: PreservingMethod, entries: HarvestEntry[], recipe: RecipeOutput) => {
      const newSaved: SavedRecipe = {
        id: generateId(),
        savedAt: new Date().toISOString(),
        name: recipe.title,
        method,
        harvestEntries: entries,
        recipe,
      };
      setSavedRecipes((prev) => [newSaved, ...prev]);
      return newSaved;
    },
    []
  );

  const deleteRecipe = useCallback((id: string) => {
    setSavedRecipes((prev) => prev.filter((r) => r.id !== id));
  }, []);

  const isRecipeSaved = useCallback(
    (recipe: RecipeOutput) => {
      // Check if a recipe with the same title, method, and total weight exists
      return savedRecipes.some(
        (r) =>
          r.recipe.title === recipe.title &&
          r.recipe.totalWeightGrams === recipe.totalWeightGrams &&
          r.recipe.method === recipe.method
      );
    },
    [savedRecipes]
  );

  return {
    savedRecipes,
    saveRecipe,
    deleteRecipe,
    isRecipeSaved,
  };
}